package kz.com.entities;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.sql.Date;

@Table(name = "project") // In this step, we create in our database the table "project"
@Data // Implementing Data from lombok annotation to automatically generate getters, setters, methods
@AllArgsConstructor // Lombok annotation to create all constructors of this class
@NoArgsConstructor // Lombok annotation to create empty constructor, by using Lombok we dont waste time to
// write down constructors, getters, setters
@Entity // represents data persisting in DataBase
public class Project {
    @Id // Pointing out that this column is ID and will be autogenerated, as well as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "name")
    private String name;

    @JsonFormat(pattern = "dd/MM/yyyy") // When we get time, it will be formatted to that pattern
    @Column(name ="start_date")
    private Date start_date;

    @JsonFormat(pattern = "dd/MM/yyyy")
    @Column(name ="end_date")
    private Date end_date;

    @Enumerated(EnumType.STRING) // Enum is dedicated to opt one of the enum value given us
    private ProjectStatus status;

    @Column(name = "priority")
    private int priority;
}

